In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [4]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent= dataset['charges']
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse'], 
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']}

In [15]:
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.710 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.454 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.753 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.605 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.652 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.709 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.591 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.738 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.564 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.724 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.643 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.561 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.592 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.589 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.545 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.655 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.570 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.694 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.641 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.607 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.553 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.388 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.710 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.571 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.623 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.411 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.567 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.540 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.411 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.624 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.609 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.547 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.682 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.593 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.643 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.674 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.650 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.727 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.574 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.685 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.592 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.467 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.765 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.186 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.609 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.658 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.600 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.495 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.668 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.547 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.624 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.586 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.656 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.635 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.616 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.547 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.630 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.553 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.562 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.590 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.703 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.480 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.764 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.623 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.662 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.633 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.670 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.690 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.679 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.674 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.582 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.558 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.656 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.679 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.626 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.512 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.503 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.632 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.608 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.597 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.248 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.495 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.669 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.481 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.593 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.589 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.486 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.557 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.653 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.629 total time=   0.0s

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [16]:

re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

In [17]:
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'}: 0.7285903745165068

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003379,0.005512,0.003082,0.005780,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.709856,0.454149,0.752561,0.604632,0.652051,0.634650,0.103289,5
1,0.003339,0.005969,0.000606,0.000810,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.709301,0.591044,0.737950,0.564014,0.723558,0.665173,0.072637,2
2,0.001595,0.000488,0.000609,0.000497,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.642810,0.561314,0.591843,0.588949,0.544699,0.585923,0.033423,11
3,0.002793,0.001001,0.001022,0.000022,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.655410,0.570067,0.694106,0.640992,0.607398,0.633595,0.042224,6
4,0.002795,0.000747,0.001001,0.000004,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.553478,0.387532,0.710286,0.571145,0.623173,0.569123,0.105899,15
5,0.002524,0.003141,0.000401,0.000491,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.410520,0.566762,0.539844,0.411332,0.623897,0.510471,0.085692,17
6,0.021198,0.004251,0.000810,0.000406,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.609267,0.546774,0.682070,0.592520,0.643410,0.614808,0.045822,9
7,0.017177,0.010201,0.000199,0.000399,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.673676,0.650200,0.726678,0.574490,0.685185,0.662046,0.050308,3
8,0.021930,0.007786,0.000309,0.000404,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.591900,0.467123,0.764831,0.185793,0.609117,0.523753,0.193636,16
9,0.004617,0.003851,0.000200,0.000399,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.657538,0.599878,0.495482,0.668369,0.547157,0.593685,0.065577,10
10,0.011377,0.007135,0.000000,0.000000,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.623738,0.586447,0.656490,0.634583,0.615565,0.623365,0.023009,7
11,0.006127,0.007506,0.000000,0.000000,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.547337,0.630019,0.552592,0.562125,0.590137,0.576442,0.030591,13
12,0.003125,0.006250,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.703011,0.479911,0.763899,0.622620,0.661880,0.646264,0.095430,4
13,0.003125,0.006249,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.633132,0.669666,0.689937,0.679169,0.673712,0.669123,0.019240,1
14,0.001196,0.001595,0.000413,0.000506,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.582253,0.557834,0.656423,0.678837,0.626257,0.620321,0.044981,8
15,0.001643,0.000832,0.000445,0.000545,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.512340,0.502919,0.632468,0.608242,0.596663,0.570527,0.052723,14
16,0.001459,0.000773,0.000798,0.000399,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.247769,0.494755,0.669266,0.480716,0.592960,0.497093,0.142316,18
17,0.002297,0.000599,0.000801,0.000400,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.589302,0.486125,0.557418,0.652640,0.629293,0.582955,0.058432,12

In [20]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:40
BMI:20
Children:1
Sex Male 0 or 1:0
Smoker Yes 0 or 1:0

In [21]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[11576.13]