In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [4]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [5]:
dependent= dataset['charges']
dependent

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse'], 
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']}

In [9]:
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=1)
# fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.720 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.623 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.720 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.699 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, splitter=best;, score=0.679 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.674 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.609 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.771 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.640 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, splitter=random;, score=0.728 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.689 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.662 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.740 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.707 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.709 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.615 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.625 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.686 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.676 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.737 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.693 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.681 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.669 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.705 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.789 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.652 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.409 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.735 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.678 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.600 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.726 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.608 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.732 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.728 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=auto, splitter=best;, score=0.742 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.711 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.597 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.725 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.690 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=auto, splitter=random;, score=0.719 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.699 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.587 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.692 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.693 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.741 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.722 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.626 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.692 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.689 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.642 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.652 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.582 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.648 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.697 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.703 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.743 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.359 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.674 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.610 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.633 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.724 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.641 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.714 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.712 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=0.677 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.719 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.513 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.756 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.737 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=0.694 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.786 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.626 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.714 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.747 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.700 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.732 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.501 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.594 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.689 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.621 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.634 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.629 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.766 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.759 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.704 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.620 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.549 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.675 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.678 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.618 total time=   0.0s

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
# Best results
print("Best Parameters:", grid.best_params_)
print("Best Cross-Validated R² Score:", grid.best_score_)

Best Parameters: {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}
Best Cross-Validated R² Score: 0.7146605889642192

In [12]:
# Store CV results in table
results_table = pd.DataFrame(grid.cv_results_)
results_table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005070,0.005495,0.003414,0.006118,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.719672,0.622646,0.720320,0.699132,0.678947,0.688143,0.036123,8
1,0.004150,0.002865,0.001195,0.001161,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.674291,0.608643,0.770745,0.639934,0.727741,0.684270,0.058570,9
2,0.003254,0.006508,0.003011,0.006022,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.689135,0.662440,0.739894,0.706918,0.708660,0.701409,0.025429,4
3,0.003844,0.006056,0.002502,0.005004,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.614738,0.624861,0.685945,0.676016,0.737440,0.667800,0.044510,13
4,0.003017,0.006034,0.006428,0.007873,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.692994,0.681427,0.668911,0.704882,0.789218,0.707486,0.042577,2
5,0.003879,0.001970,0.001231,0.001041,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.652150,0.409471,0.735433,0.677770,0.599643,0.614894,0.111626,17
6,0.028653,0.004569,0.000000,0.000000,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.725889,0.607603,0.732358,0.728125,0.741761,0.707147,0.050068,3
7,0.030807,0.007851,0.001009,0.001279,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.710995,0.596682,0.725027,0.689843,0.719181,0.688346,0.047358,7
8,0.024535,0.006810,0.000399,0.000489,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.699113,0.586773,0.691949,0.692785,0.740926,0.682309,0.051084,11
9,0.013605,0.004320,0.000000,0.000000,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.722483,0.625563,0.691537,0.689479,0.641693,0.674151,0.035461,12
10,0.024330,0.007814,0.001001,0.001264,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.651857,0.581772,0.648262,0.696808,0.703200,0.656380,0.043541,14
11,0.017114,0.003870,0.000599,0.001197,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.743214,0.358895,0.673778,0.610348,0.632837,0.603814,0.130535,18
12,0.004142,0.007351,0.003675,0.006399,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.723648,0.641485,0.713901,0.711796,0.676715,0.693509,0.030487,6
13,0.000799,0.001598,0.006752,0.007962,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.719034,0.513345,0.756202,0.736920,0.693838,0.683868,0.087705,10
14,0.003517,0.000450,0.005578,0.008666,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.785670,0.626291,0.714395,0.746730,0.700218,0.714661,0.053082,1
15,0.002997,0.001101,0.001724,0.001005,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.731629,0.501041,0.593955,0.688606,0.620553,0.627157,0.079676,16
16,0.003126,0.006252,0.003125,0.006250,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.634309,0.629396,0.766110,0.758783,0.703554,0.698430,0.058526,5
17,0.003123,0.006246,0.000000,0.000000,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.619821,0.548611,0.675306,0.677838,0.617819,0.627879,0.047318,15

In [13]:
# Future prediction
age_input = float(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = float(input("Children: "))
sex_male_input = int(input("Sex Male (0 or 1): "))
smoker_yes_input = int(input("Smoker Yes (0 or 1): "))

Age: 45
BMI: 26
Children: 1
Sex Male (0 or 1): 1
Smoker Yes (0 or 1): 0

In [14]:
future_prediction = grid.best_estimator_.predict(
    [[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]]
)
print("Predicted Insurance Charges:", future_prediction)

Predicted Insurance Charges: [7518.02535]

C:\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"