In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [5]:
dependent= dataset['charges']

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [13]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error'],
             'max_features': ['auto','sqrt','log2'],
             'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=1)
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.856 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.732 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.794 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.776 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.769 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.863 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.766 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.815 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.798 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.772 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.838 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.768 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.787 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.799 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.767 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.858 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.793 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.807 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.827 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.771 total time=   0.1s
[CV 1/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.851 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.776 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.738 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.792 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.743 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.865 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.797 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.810 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.834 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.771 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.839 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.781 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.793 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.777 total time=   0.1s
[CV 5/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.759 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.849 total time=   1.2s
[CV 2/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.775 total time=   1.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.795 total time=   1.1s
[CV 4/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.799 total time=   1.3s
[CV 5/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.767 total time=   1.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.831 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.787 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.783 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.834 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.754 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.863 total time=   0.6s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.786 total time=   0.6s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.811 total time=   0.6s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.829 total time=   0.6s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.771 total time=   0.7s
[CV 1/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.834 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.764 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.802 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.819 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.765 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.858 total time=   0.6s
[CV 2/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.793 total time=   0.5s
[CV 3/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.807 total time=   0.6s
[CV 4/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.824 total time=   0.7s
[CV 5/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.765 total time=   0.7s

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [14]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)
# print classification report
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}: 0.8703570071539272

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.030148,0.009626,0.000607,0.000802,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",0.855840,0.731790,0.794081,0.776171,0.768885,0.785353,0.040667,11
1,0.228306,0.042721,0.001773,0.003546,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.863289,0.766000,0.815483,0.797810,0.772025,0.802921,0.035060,5
2,0.023065,0.009266,0.000000,0.000000,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.838031,0.767680,0.786979,0.798817,0.767201,0.791742,0.026064,9
3,0.196097,0.046493,0.012255,0.005507,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857984,0.792595,0.807306,0.826559,0.770951,0.811079,0.029685,3
4,0.026573,0.008631,0.003325,0.006163,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.850563,0.775522,0.737906,0.791891,0.743349,0.779846,0.040634,12
5,0.221763,0.043790,0.007001,0.006128,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.865402,0.796768,0.809889,0.834333,0.770878,0.815454,0.032306,1
6,0.114714,0.032062,0.000606,0.000811,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",0.838904,0.780529,0.792764,0.776993,0.758941,0.789626,0.026915,10
7,1.222563,0.090822,0.011136,0.006363,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.849349,0.775388,0.795331,0.799333,0.766620,0.797204,0.028770,7
8,0.062987,0.018218,0.005743,0.007081,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.830601,0.786713,0.782595,0.833704,0.753548,0.797432,0.030583,6
9,0.699183,0.040843,0.003873,0.006357,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.863336,0.785753,0.811286,0.829083,0.770992,0.812090,0.032552,2
10,0.091231,0.014108,0.000683,0.000939,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.833935,0.763730,0.801660,0.819448,0.765219,0.796798,0.028307,8
11,0.709141,0.059936,0.004161,0.005157,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.858223,0.792752,0.807454,0.823912,0.765395,0.809547,0.031021,4

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:57
BMI:35
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[15236.1355048]