In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
independent= dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [5]:
dependent= dataset['charges']

In [8]:
from sklearn.ensemble import RandomForestRegressor

In [9]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error'],
             'max_features': ['auto','sqrt','log2'],
             'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=1)
# fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.825 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.749 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.857 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.809 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=auto, n_estimators=10;, score=0.829 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.851 total time=   0.3s
[CV 2/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.771 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.858 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.821 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=auto, n_estimators=100;, score=0.838 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.853 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.765 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.841 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.815 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, n_estimators=10;, score=0.843 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.862 total time=   0.1s
[CV 2/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.778 total time=   0.2s
[CV 3/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.858 total time=   0.1s
[CV 4/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.827 total time=   0.2s
[CV 5/5] END criterion=squared_error, max_features=sqrt, n_estimators=100;, score=0.838 total time=   0.2s
[CV 1/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.844 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.764 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.851 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.812 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, n_estimators=10;, score=0.826 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.857 total time=   0.2s
[CV 2/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.776 total time=   0.1s
[CV 3/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.863 total time=   0.2s
[CV 4/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.831 total time=   0.1s
[CV 5/5] END criterion=squared_error, max_features=log2, n_estimators=100;, score=0.839 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.818 total time=   0.1s
[CV 2/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.753 total time=   0.1s
[CV 3/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.841 total time=   0.1s
[CV 4/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.810 total time=   0.1s
[CV 5/5] END criterion=absolute_error, max_features=auto, n_estimators=10;, score=0.838 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.840 total time=   1.7s
[CV 2/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.768 total time=   2.0s
[CV 3/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.853 total time=   1.9s
[CV 4/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.825 total time=   1.6s
[CV 5/5] END criterion=absolute_error, max_features=auto, n_estimators=100;, score=0.835 total time=   2.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.836 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.762 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.841 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.816 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, n_estimators=10;, score=0.827 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.855 total time=   1.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.780 total time=   1.1s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.856 total time=   1.1s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.829 total time=   1.2s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, n_estimators=100;, score=0.844 total time=   1.1s
[CV 1/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.850 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.763 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.853 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.795 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, n_estimators=10;, score=0.833 total time=   0.1s
[CV 1/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.852 total time=   1.2s
[CV 2/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.780 total time=   1.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.857 total time=   0.9s
[CV 4/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.829 total time=   1.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, n_estimators=100;, score=0.843 total time=   0.9s

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
# Best results
print("Best Parameters:", grid.best_params_)
print("Best Cross-Validated R² Score:", grid.best_score_)

Best Parameters: {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}
Best Cross-Validated R² Score: 0.8331232877139885

In [11]:
# Store CV results in table
results_table = pd.DataFrame(grid.cv_results_)
results_table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.034632,0.007806,0.008005,0.006452,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",0.824797,0.749452,0.856938,0.808955,0.829216,0.813872,0.035731,11
1,0.288481,0.042775,0.013266,0.003458,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",0.850863,0.771323,0.858275,0.820594,0.838430,0.827897,0.031032,5
2,0.025978,0.006658,0.006661,0.007361,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.852934,0.765147,0.840606,0.814826,0.843228,0.823348,0.031712,7
3,0.243445,0.025621,0.014758,0.004428,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.862140,0.778099,0.857662,0.826955,0.838489,0.832669,0.030125,3
4,0.025475,0.004123,0.005118,0.005424,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844392,0.763702,0.851115,0.812143,0.825654,0.819401,0.031063,8
5,0.222219,0.032617,0.013718,0.009334,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856624,0.775675,0.863381,0.830950,0.838987,0.833123,0.031007,1
6,0.195306,0.013548,0.003917,0.006041,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",0.818079,0.752539,0.840997,0.810412,0.837780,0.811961,0.031876,12
7,1.920433,0.171308,0.011311,0.006204,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",0.839975,0.767859,0.852621,0.824564,0.834674,0.823939,0.029463,6
8,0.111138,0.010357,0.004134,0.005881,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.835881,0.761793,0.840751,0.815958,0.826665,0.816210,0.028495,10
9,1.198695,0.059320,0.012014,0.007364,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.854898,0.780413,0.856498,0.828918,0.844075,0.832960,0.028059,2
10,0.134552,0.025347,0.000798,0.000977,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.850377,0.762585,0.853348,0.795292,0.833345,0.818990,0.034971,9
11,1.071357,0.112019,0.012792,0.003883,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.851590,0.779659,0.856994,0.828854,0.842935,0.832006,0.027848,4

In [12]:
# Future prediction
age_input = float(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = float(input("Children: "))
sex_male_input = int(input("Sex Male (0 or 1): "))
smoker_yes_input = int(input("Smoker Yes (0 or 1): "))

Age: 45
BMI: 33
Children: 3
Sex Male (0 or 1): 1
Smoker Yes (0 or 1): 1

In [13]:
future_prediction = grid.best_estimator_.predict(
    [[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]]
)
print("Predicted Insurance Charges:", future_prediction)

Predicted Insurance Charges: [42166.8731027]

C:\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"